Added a Config for RefuelSpeed
MarkusA380/SimpleRefuel pull request #2
Opened 2018-03-22 02:16 UTC by ijzm

Hello! I saw this simple mod the other day and really liked it. The only problem is that I thought the speed for refueling is way too slow.

I added a SimpleRefuel.cfg file, that allows any user to change the refuel speed. I set it as 10.0 as you had in your file before, but just changing that number will make things way faster.

I might look at being able to add more refueling zones accross Kerbin (for example in the Airfield, and the new launchpad)

2018-03-23 07:13 UTC, MarkusA380 commented
I'm happy you like the mod, and I think your work is a great addition!
I will review it as soon as possible.

Can you give me your KSP forums account name, so I can add you to the list of contributors in the according thread?

2018-03-23 13:12 UTC, ijzm commented
My account name is ijzm - https://forum.kerbalspaceprogram.com/index.php?/profile/187140-ijzm/

I'm glad you liked it. I might work a bit more on it later.

2018-03-23 13:45 UTC, MarkusA380 commented
I would be more than happy to see more pull requests from you! 😄 
Before I merge, can you change your variable naming according to my comments?
I am using the same naming convention as the KSP API does.

2018-03-23 13:46 UTC, markusa380 requested changes

2018-03-23 13:46 UTC, MarkusA380 commented on Source/Config.cs
> +		private const string _configFilePath = "GameData/SimpleRefuel/SimpleRefuel.cfg";
Underscores should be used for temporary variables only. It is hardcoded anyway, so placing the literal string into the getter of ConfigFilePath makes more sense.

2018-03-23 13:46 UTC, MarkusA380 commented on Source/Config.cs
> +		private const string SettingsNodeName = "SimpleRefuel_Settings";
This project is using camel case with small initial letters for variables.

2018-03-23 13:46 UTC, MarkusA380 commented on Source/Config.cs
> +		private static Config _instance;
Please do not use underscores in variables.

2018-03-23 13:46 UTC, MarkusA380 commented on Source/Config.cs
> +		private void _load() {
Please do not use underscores for methods. Methods should have an uppercase first letter.

2018-03-23 13:50 UTC, ijzm commented
I'm not going to be home for about 5 more hours,  but as soon as I get there I'll do those changes. Thanks for the feedback!

2018-03-24 01:47 UTC, ijzm commented
Just did the changes you asked, hopefully everything is alright now. :D

2018-03-24 13:36 UTC, merged